### ISSUE TITLE
Category logic/fetching

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Backend#12]
## User Story
As someone who likes playing guessing/drawing games, I enjoy having a wide variety of topics to guess or draw from. If the game only has one main topic it gets boring and predictable and is not as fun. I prefer games that have more variety to them.

- Persona: A person who enjoys drawing/guessing games.
- Feature: Allowing player to choose from a randomized selection of categories 
- Business Value: Players feel the game is less repetitive when given more options

## Tasks
- [x] connect to MongoDB from backend
- [x] query categories to be selected for category page
- [x] display categories on page
- [x] randomize selection and pick 3
- [x] query word from chosen category (according to votes)
- [x] randomize selection - pick one

## Acceptance Criteria
- read permission credentials are to be used for database connection
- The categories should be properly displayed on category page
- Data is queried properly
