### ISSUE TITLE
Category voting [backend]

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Backend#13]
### User Story
As someone who enjoys playing games, I always like having freedom of choice when the game has multiple topics. I don't enjoy games that have a fixed number of topics that are chosen by the game itself. When I'm given different choices every time also makes the game more replayable and more interesting.

- Persona: A user who enjoys playing drawing/guessing games
- Feature: Users get to choose a category from a random selection
- Business Value: makes the game more replayable, gives user freedom of choice making the game more interesting.

### Tasks
- [ ] after voting time is completed, acquire total number of votes
- [ ] keep track of votes for each category, pick category with largest amount of votes
- [ ] On ties, pick randomly
- [ ] the winning category/word should be sent to the frontend (so the frontend can display)

### Acceptance Criteria
- If a tie happens the game should pick randomly from the categories included in the tie
- Each user's vote counts the same
- Users can only vote in one category at a time.

**Comment by eyu776** [comment]
commit ccf5fd3 by Ali seems to solve this issue...?
