### ISSUE TITLE
Guess Voting/Scoring [Backend]

### ISSUE THREAD

**Issue by StellarSparks** [COSC481W-2024Winter/Fictionary-Backend#14]
### User Story:

As someone who plays games with different roles, I like it when the point distribution is balanced between roles. It can get frustrating when one role has an easier time winning than others.

**Persona:** Someone who plays games with different roles.
**Feature:** A balanced scoring system.
**Business Value:** Players will find the game less frustrating and be more likely to keep playing.

### Tasks: 

- [x] Count the votes cast for each guess
- [x] Award points based on the roles in the game
- [x] Keep track of the players' total scores as well as their artist scores and trickster scores

### Acceptance Criteria: 

- "Trickster" points and "artist" points should be tracked separately.
- The scoring system should be balanced (e.g. the artist should earn double the points of the tricksters if their drawing is good enough for someone to guess the prompt word, since tricksters will also score bonus points for guessing the prompt word correctly instead of being tricked)
- Players that trick other tricksters into picking a wrong answer will steal points from the players that guessed
- If a player has no points but makes an incorrect guess, they will not lose any points but the trickster will still earn a point for their trick.
