### ISSUE TITLE
Chat Functionality

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Backend#16]
## User Story
As someone who enjoys multiplayer games, I believe one of the most important aspects of it is communication between players. Making a chat in an online game makes you feel lie other people you are playing with are real. I especially enjoy it when I'm playing with friends so I can talk to them.

- Persona: A person who enjoys multiplayer games (age varies)
- Feature: A chat area where players can communicate
- Business Value: players feel like they are playing a multiplayer game. They can communicate with other players adding an extra layer of entertainment in the game.

## Tasks
- [ ] Receive user's message
- [ ] transmit message to all users
- [ ] Update UI for chat messages

## Acceptance criteria
- Artist can see messages but can't type
- Non-artists can both send and view messages
- Messages are seen by everyones and there is no private message system
