### ISSUE TITLE
Lobby functionality

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Backend#2]
## user story
As a person who enjoys online games, I like to customize by gamer tag when I play games and I want to choose my own. When I enter a web based game I want to see who is in the room, especially when I host the match. Otherwise, I can't tell if I can start the game yet, since I might be missing some friends.

- Persona: A player that is interested in web based games, age can vary
- Feature: See names of players currently on lobby
- Business Value: Other players can see their friends on the lobby and host knows if he can start the game (once all participants are there)

## Tasks
- [x] Take in users name;
- [x] Communicate to backend and update in the UI
- [x] Create user list (per room)
- [x] Update list on user enter/leave
- [x] Re-render page when player enter/leaves; 
- [x] Implement basic input validation

## Acceptance criteria
- Host can start game when clicking start button 
- Non-host players cannot start the game
- Game can only start when there is 3 people in the room
- Regular user should only be able to join existing room
- Host should have designation in the UI

**Comment by BelaReimberg** [comment]
Reviewed/ Accepted pull request 
#9
