### ISSUE TITLE
Implement Dynamic Rendering Base

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Backend#3]
## User story
I want to play a game that feels complete and has each part working well. I get annoyed when games glitch and I get the wrong page displayed to me for no apparent reason. When this happens it ends up being game breaking and I don't feel like playing the game anymore.

## Tasks 
- [ ] Clarify user roles (artist, host, guessers)
- [ ] Create general flow of operation 
- [ ] Create proper conditions for the display of each component

## Acceptance Criteria
The following pages remain static:
- Home page
- Rules page
- Host page 
- Guest/Join 

The following pages are dynamic:
- Begin at lobby 
- Categories voting
- Drawing
- Voting
- Results
- Scoreboard 

- Should be able to go through general logic of the game; flow should be established 
- Should be accomplished on one singular page
- Should have understandable and readable code - this page will be the main aspect of the game and needs to be well documented and organized.
