### ISSUE TITLE
Setup deployment

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Backend#6]
## Task
- [x] Read Digital Ocean use specifications
- [x] Understand how to deploy both front and back end sides
- [x] Communicate with professor to be included in the group to obtain the paid-for tier (if we aren't already)

## Acceptance criteria
- Front and back end are each deployed separately
