### ISSUE TITLE
Setup testing framework

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Backend#8]
(doesn't need user story)

## Tasks
- [ ] Download Jest : https://jestjs.io/
- [ ] Set testing framework for the project
- [ ] Lay out steps on how to use tests

## Acceptance Criteria
- Jest should be set up meaning other members can build additional tester functions without additional configuration
